# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='image',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
